Fix Issue #22: Adjust .project__buttons position
harshitg123/portfolio pull request #25
Opened 2024-07-30 09:23 UTC by FullStackWebDeveloper-HARSH

**Fix Issue #22: Adjust .project__buttons Position**

**Description:**
->This PR addresses Issue #22 by adjusting the position of the .project__buttons div to move it slightly upwards. The changes involve adding a new CSS class .robotic-view with position: relative and top: -1rem to shift the buttons upwards.

**Changes:**
->Added a new CSS class .robotic-view to adjust the top property and move the .project__buttons div upwards.
->Updated the HTML to include the .robotic-view class for the relevant div.

**Before:**
The .project__buttons div was positioned lower than desired, causing a misalignment in the layout.

**After:**
The .project__buttons div is now positioned higher, providing a more visually appealing and aligned layout.

**Testing:**
->Verified that the buttons are correctly aligned across different screen sizes.
->Ensured that the layout remains responsive and visually consistent.

<img width="574" alt="image" src="https://github.com/user-attachments/assets/5af74247-39be-4943-abc2-129a7ec4c88c">

**Related Issues:** Fixes #22

**Additional Notes:**
Please review the changes and let me know if there are any further adjustments needed. Thank you!

2024-07-31 15:01 UTC, harshitgupta028 requested changes
Hi @FullStackWebDeveloper-HARSH,

I want to thank you for your solution, but it won't completely solve the problem. It only addresses the alignment issue for one card and is not responsive. Additionally, we would still need to manually align the buttons with another card's button.

Instead, I suggest applying a specific height to the description section of the cards. This will provide equal space for the description section of all cards, ensuring that all buttons render properly. I've attached a screenshot for your reference.

I appreciate it if you could submit a PR with this change.

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/6af91ebd-2a2a-4bf8-be55-7404d25e40f9">

In screenshot, you can see after applying the height to the description all the buttons get self-aligned.

2024-08-01 15:48 UTC, FullStackWebDeveloper-HARSH commented
<img width="592" alt="image" src="https://github.com/user-attachments/assets/95f0a775-2b76-4540-a92f-5aae36cc7cfa">

Hi Harsit,
The addition of height: 10rem to the project description class was intended to standardize the height across all cards. However, the change didn't fully address the alignment and responsiveness issues. Some cards still appear misaligned, especially on different screen sizes, and the fixed height doesn't provide enough flexibility for varying content lengths.

2024-08-02 08:27 UTC, harshitgupta028 commented
Hi @FullStackWebDeveloper-HARSH, yes it will happen because if you see the skill section there is `min-height` in that section change it to a fixed `height` of 4rem.

![image](https://github.com/user-attachments/assets/b7a007b4-c92f-4381-87f9-e83a4f43f5b3)

This is the one solution to make it more robust you can handle having the beautiful scroll on the x-axis in case there is more skill which will overlap more than 2 lines.

2024-08-02 10:58 UTC, FullStackWebDeveloper-HARSH commented
Hi Harshit,

I wanted to inform you that I've made a minor update to the .project__skills__Container class in the project. I increased the height from the previous value to 4rem. This change improves the layout consistency across different screen sizes, ensuring that the section looks better aligned.

Please let me know if you have any feedback or if there's anything else you'd like me to adjust.

Best regards,
Harsh Tiwari

2024-08-02 13:37 UTC, harshitgupta028 approved these changes
Hi @FullStackWebDeveloper-HARSH,

It is good now. Thanks

regards,
Harshit Gupta

2024-08-02 13:37 UTC, harshitgupta028 commented on public/css/styles.css
> +  /* min-height: 3.5rem; */
good you commented it instead of removing it.

2024-08-02 13:38 UTC, merged